# This is just an example workflow for continuous deployment.
# You should customize it to meet your own requirements.
name: 'Bot msg CD'

trigger:
# When new commits are pushed onto the main branch.
- tmtestbotmsg

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: buildAndPublish
  steps:
    - task: NodeTool@0
      displayName: Setup environment
      inputs:
        versionSpec: '14.x'
        checkLatest: true

    # Checkout the code
    - checkout: git://demo/teamsfx-cli-action-azuretest@tmtestbotmsg

    - task: Bash@3
      displayName: Generate default.userdata
      env:
        USERDATA_TENANT_ID: $(USERDATA_TENANT_ID)
        USERDATA_CLIENT_SECRET: $(USERDATA_CLIENT_SECRET)
        USERDATA_BOT_PASSWORD: $(USERDATA_BOT_PASSWORD)
      inputs:
        targetType: 'inline'
        script: |
          [ ! -z "${USERDATA_TENANT_ID}" ] && echo "solution.teamsAppTenantId=${USERDATA_TENANT_ID}" >> .fx/default.userdata
          [ ! -z "${USERDATA_CLIENT_SECRET}" ] && echo "fx-resource-aad-app-for-teams.clientSecret=${USERDATA_CLIENT_SECRET}" >> .fx/default.userdata
          [ ! -z "${USERDATA_BOT_PASSWORD}" ] && echo "fx-resource-bot.botPassword=${USERDATA_BOT_PASSWORD}" >> .fx/default.userdata

    - task: teamsfx-cli-task@1
      displayName: Deploy to hosting environment
      env:
        AZURE_ACCOUNT_NAME: $(AZURE_ACCOUNT_NAME)
        AZURE_ACCOUNT_PASSWORD: $(AZURE_ACCOUNT_PASSWORD)
        AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
        AZURE_TENANT_ID: $(AZURE_TENANT_ID)
        M365_ACCOUNT_NAME: $(M365_ACCOUNT_NAME)
        M365_ACCOUNT_PASSWORD: $(M365_ACCOUNT_PASSWORD)
      inputs:
        commands: deploy

    # This step is to pack the Teams App as zip file,
    # which can be used to be uploaded onto Teams Client for installation.
    - task: teamsfx-cli-task@1
      displayName: Package Teams App for publishing
      inputs:
        commands: build

    - task: PublishBuildArtifacts@1
      displayName: Upload Teams App's package as artifact
      inputs:
        PathtoPublish: appPackage/appPackage.zip
        ArtifactName: 'appPackage'
        publishLocation: 'Container'

    - task: teamsfx-cli-task@1
      displayName: Publish Teams App
      env:
        M365_ACCOUNT_NAME: $(M365_ACCOUNT_NAME)
        M365_ACCOUNT_PASSWORD: $(M365_ACCOUNT_PASSWORD)
      inputs:
        commands: publish
