name: Alisa Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
      AZURE_ACCOUNT_PASSWORD: ${{secrets.AZURE_ACCOUNT_PASSWORD}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      M365_ACCOUNT_NAME: ${{secrets.M365_ACCOUNT_NAME}}
      M365_ACCOUNT_PASSWORD: ${{secrets.M365_ACCOUNT_PASSWORD}}
      M365_TENANT_ID: ${{secrets.M365_TENANT_ID}}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with: 
          repository: OfficeDev/teamsfx-cli-action
          token: ${{secrets.MY_TOKEN}}
      
      - name: Run a one-line script
        run: echo Hello, world!