name: SPFx Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
      AZURE_ACCOUNT_PASSWORD: ${{secrets.AZURE_ACCOUNT_PASSWORD}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      M365_ACCOUNT_NAME: ${{secrets.TMTEST_M365_ACCOUNT_NAME}}
      M365_ACCOUNT_PASSWORD: ${{secrets.TMTEST_M365_ACCOUNT_PASSWORD}}
      M365_TENANT_ID: ${{secrets.TMTEST_M365_TENANT_ID}}
      CI_ENABLED: true

    steps:
      - name: Setup root project
        uses: actions/checkout@v2
        with: 
          ref: refs/heads/spfxproject

      - name: Setup repo
        uses: actions/checkout@v2
        with: 
          repository: OfficeDev/teamsfx-cli-action
          ref: refs/heads/test
          token: ${{secrets.MY_TOKEN}}
          path: ./.github/actions/awesome-action

      - uses: ./.github/actions/awesome-action
        with:
          commands: provision
      
      - uses: ./.github/actions/awesome-action
        with:
          commands: deploy

      - name: Upload sppkg file
        uses: actions/upload-artifact@v2
        with:
          name: spfxproject_sppkg_zip
          path: ./SPFx/sharepoint/solution/*.sppkg

      - uses: ./.github/actions/awesome-action
        with:
          commands: validate
      
      - uses: ./.github/actions/awesome-action
        with:
          commands: build

      - name: Upload build file
        uses: actions/upload-artifact@v2
        with:
          name: BuildingappPackage_zip
          path: ./.fx/appPackage.zip

      - uses: ./.github/actions/awesome-action
        with:
          commands: publish