name: Alisa Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
      AZURE_ACCOUNT_PASSWORD: ${{secrets.AZURE_ACCOUNT_PASSWORD}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      M365_ACCOUNT_NAME: ${{secrets.M365_ACCOUNT_NAME}}
      M365_ACCOUNT_PASSWORD: ${{secrets.M365_ACCOUNT_PASSWORD}}
      M365_TENANT_ID: ${{secrets.M365_TENANT_ID}}

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with: 
          repository: OfficeDev/teamsfx-cli-action
          ref: refs/heads/test
          token: ${{secrets.MY_TOKEN}}
          path: ./.github/actions/awesome-action
      
      - uses: ./.github/actions/awesome-action
        with:
          commands: new
          interactive: false
          app-name: alisaa001
          capabilities: |
            tab
            bot

      - uses: ./.github/actions/awesome-action
        with:
          commands: new
          interactive: false
          app-name: hellyspfx07201304
          host-type: spfx
          spfx-framework-type: react
          programming-language: typescript
          spfx-webpart-name: helloworld

      - uses: ./.github/actions/awesome-action
        with:
          commands: new
          interactive: false
          app-name: ruhe07161043
          capabilities: |
            tab
            bot

      - uses: ./.github/actions/awesome-action
        with:
          commands: provision
          folder: ./ruhe07161043
          subscription: ${{env.AZURE_SUBSCRIPTION_ID}}
      
      - uses: ./.github/actions/awesome-action
        with:
          commands: deploy
          folder: ./ruhe07161043

      - uses: ./.github/actions/awesome-action
        with:
          commands: validate
          folder: ./ruhe07161043
      
      - uses: ./.github/actions/awesome-action
        with:
          commands: build
          folder: ./ruhe07161043

      - uses: ./.github/actions/awesome-action
        with:
          commands: publish
          folder: ./ruhe07161043
