name: SPFx Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
      AZURE_ACCOUNT_PASSWORD: ${{secrets.AZURE_ACCOUNT_PASSWORD}}
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      M365_ACCOUNT_NAME: ${{secrets.M365_ACCOUNT_NAME}}
      M365_ACCOUNT_PASSWORD: ${{secrets.M365_ACCOUNT_PASSWORD}}
      M365_TENANT_ID: ${{secrets.M365_TENANT_ID}}
      APP_NAME: hellytest0727

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with: 
          repository: OfficeDev/teamsfx-cli-action
          ref: refs/heads/test
          token: ${{secrets.MY_TOKEN}}
          path: ./.github/actions/awesome-action

      - uses: ./.github/actions/awesome-action
        with:
          commands: provision
      
      - uses: OfficeDev/teamsfx-cli-action@test
        with:
          commands: new
          interactive: false
          app-name: ${{env.APP_NAME}}
          capabilities: tab
          azure-resources: |
            sql
            function

      - uses: OfficeDev/teamsfx-cli-action@test
        with:
          commands: provision
          folder: ./${{env.APP_NAME}}
          subscription: ${{env.AZURE_SUBSCRIPTION_ID}}
          sql-admin-name: ${{env.APP_NAME}}
          sql-password: qwer@1234

      - name: Upload project file
        uses: actions/upload-artifact@v2
        with:
          name: project_zip
          path: ./