# This is just an example workflow for continuous integration.
# You should customize it to meet your own requirements.
name: 'testwin'
on:
  # Manually trigger this workflow, and you should pick the right branch.
  workflow_dispatch:
    inputs:
      tag:
        description: 'vsix release tag. e.g. stable, rc or leave it empty to use latest daily release'
        required: false
  push:
   branches:
    - main
    - dev
    - rc
  
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cases: ${{steps.job1.outputs.cases}}
      tv2: ${{steps.job1.outputs.tv2}}
    steps:
      - name: echo element
        id: job1
        run: |
          echo "::set-output name=cases::[10]"
          echo "::set-output name=tv2::test-tv2"
      - name: get attempts2
        run: |
          if [ "${{ github.event_name }}" != 'push2' ]; then
            echo push4
          else
            if [ "${{ github.event_name }}" == 'push' ]; then
              echo push2
            else
              echo push3
            fi            
          fi

