# This is just an example workflow for continuous integration.
# You should customize it to meet your own requirements.
name: 'uitest'
on:
  # Manually trigger this workflow, and you should pick the right branch.
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      M365_USERNAME1: test04@xxbdw.onmicrosoft.com
    outputs:
      cases: ${{steps.job1.outputs.cases}}
      tv2: ${{steps.job1.outputs.tv2}}
    steps:

      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install npm packages
        run: |
          npm install

      - name: Set azure account (ubuntu)
        run: |
          username='${{ secrets.M365_USERNAME }}'
          echo "M365_USERNAME=$username" >> $GITHUB_ENV

      - name: Use the value
        run: |
          echo "${{ env.M365_USERNAME }}"

      - name: Set azure account1 (ubuntu)
        run: |
          a="1"
          username1='${{ secrets.M365_USERNAME_1 }}'
          username2='${{ secrets.M365_USERNAME_2 }}'
          username="username$a"
          echo "M365_USERNAME=${!username}" >> $GITHUB_ENV
          echo ${{ github.job }}

      - name: Use the value1
        run: |
          echo "${{ env.M365_USERNAME }}"


      - name: echo env
        run: |
          npx ts-node src/a.ts

