# This is just an example workflow for continuous integration.
# You should customize it to meet your own requirements.
name: 'uitest'
on:
  # Manually trigger this workflow, and you should pick the right branch.
  workflow_dispatch:
    inputs:
      target-testplan-name:
          description: "For example: CY230919. Sync test result to this test plan."
          required: false
          type: string
  
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      M365_USERNAME1: test04@xxbdw.onmicrosoft.com
    steps:

      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install npm packages
        run: |
          npm install

      - name: Set azure account (ubuntu)
        run: |
          username='${{ secrets.M365_USERNAME }}'
          echo "M365_USERNAME=$username" >> $GITHUB_ENV

      - name: Use the value
        run: |
          echo "${{ env.M365_USERNAME }}"

      - name: Use the runid
        run: |
          echo "job id:"
          echo "${{ github.job }}"


      - name: Set azure account1 (ubuntu)
        run: |
          a="1"
          username1='${{ secrets.M365_USERNAME_1 }}'
          username2='${{ secrets.M365_USERNAME_2 }}'
          username="username$a"
          echo "M365_USERNAME=${!username}" >> $GITHUB_ENV


      - name: Use the value1
        run: |
          echo "${{ env.M365_USERNAME }}"

  test-plan-update1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: echo target-testplan-name1
        run: |
          echo "${{ github.event.inputs.target-testplan-name }}"


  test-plan-update:
    needs: setup
    if: ${{ github.event.inputs.target-testplan-name != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: echo target-testplan-name
        run: |
          echo "${{ github.event.inputs.target-testplan-name }}"

  test-matrix1:
    needs: setup
    strategy:
      matrix:
        node-version: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        node-version2: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    steps:
      - name: echo target-testplan-name
        run: |
          echo1 ${{ matrix.node-version }}

  test-matrix2:
    needs: setup
    strategy:
      matrix:
        node-version: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
        node-version2: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    steps:
      - name: echo target-testplan-name
        run: |
          echo matrix2
          echo2 ${{ matrix.node-version }}
