# This is just an example workflow for continuous integration.
# You should customize it to meet your own requirements.
name: 'test-yml-win'
on:
  # Manually trigger this workflow, and you should pick the right branch.
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: windows-latest
    env:
      M365_USERNAME1: test04@xxbdw.onmicrosoft.com
    outputs:
      cases: ${{ steps.env-a.outputs.cases }}
    steps:

      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install npm packages
        run: |
          npm install

      - name: set env
        id: env-a
        run: |
          echo "cases=This is cases variable" >> $env:GITHUB_OUTPUT

      - name: get env
        run: |
          $users=@("${{ secrets.M365_USERNAME }}","${{ secrets.M365_USERNAME_2 }}","${{ secrets.M365_USERNAME_3 }}","${{ secrets.M365_USERNAME_4 }}")
          $index=Get-Random -min 0 -max $users.length
          $user=$users[$index]
          echo "account index: $index"
          echo "AZURE_ACCOUNT_NAME=$user" >> $env:GITHUB_ENV

      - name: echo env
        run: |
          npx ts-node src/a.ts

  main:
    name: main
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: in main
        run: |
          echo main

  report:
    needs: [setup, main]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Environment
        run: |
          echo "This is in double quotation marks"
          echo 'This is in single quotation mark'
          echo This is not in quotation marks
