# This is just an example workflow for continuous integration.
# You should customize it to meet your own requirements.
name: 'test-yml'
on:
  # Manually trigger this workflow, and you should pick the right branch.
  workflow_dispatch:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      M365_USERNAME1: test04@xxbdw.onmicrosoft.com
    outputs:
      cases: ${{ steps.env-a.outputs.cases }}
    steps:

      - name: Checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install npm packages
        run: |
          npm install

      - name: set env
        id: env-a
        run: |
          echo "cases=This is cases variable" >> $GITHUB_OUTPUT

      - name: set env3
        run: |
          users=("${{ secrets.M365_USERNAME }}" "${{ secrets.M365_USERNAME_2 }}" "${{ secrets.M365_USERNAME_3 }}" "${{ secrets.M365_USERNAME_4 }}")
          count=${#users[@]}
          index=$((RANDOM%$count))
          echo "account index: $index"
          echo "AZURE_ACCOUNT_NAME=${users[index]}" >> $GITHUB_ENV

      - name: echo env
        run: |
          npx ts-node src/a.ts

  main:
    name: main
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: in main
        if: contains('aHelloTest', 'hello')
        run: |
          echo main1

      - name: Setup node 2
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: node version
        run: |
          node -v

      - name: Send E-mail
        run: |
          response=$(curl \
            --request POST \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data "grant_type=client_credentials&client_id=f267696e-11b9-4c8a-8161-526b2cf84cfa&client_secret=${{ secrets.aadtoken }}&resource=https://management.core.windows.net" \
            "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token")

          token=`echo $response | jq -r '. | select(.access_token) | .access_token'`

          curl \
            --request POST \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer $token" \
            --data '{"to": "v-helzha@microsoft.com", "emailbody": "test-body", "subject": "test-title"}' \
            'https://prod-79.eastus.logic.azure.com:443/workflows/cd1047f914534ad28b4bf2cad679b1af/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0'

  report:
    needs: [setup, main]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Environment
        run: |
          echo "This is in double quotation marks"
          echo 'This is in single quotation mark'
          echo This is not in quotation marks
